### ISSUE TITLE
Metro Exodus Enhanced seems to work fine

### ISSUE THREAD

**Issue by Larkonian** [emoose/DLSSTweaks#11]
Needs OverrideAppId = true to respect AI model.

Works with both the developer DLL and the original 2.1.55 DLL.

I only played it for a few minutes but didn't notice any artifacts.

You must rename dxgi.dll to Xnput1_3.dll for the hook to work.

**Comment by Biasio95** [comment]
For me Metro exodus enhanced crashes with the dxgi.dll, doesn't work with XInput1_3.dll, but works fine if I use XInput9_1_0.dll.
I'm using dlss ver 3.1.1 from techpowerup's page.

**Comment by Larkonian** [comment]
Yes, I forgot that part. I have updated the first post.

**Comment by emoose** [comment]
Thanks for the info, added it to the readme, guess maybe the DLL names depends which store version you own? Not sure, I mentioned them both anyway.
