### ISSUE TITLE
Is it possible to switch presets in-game?

### ISSUE THREAD

**Issue by Nathan240600** [emoose/DLSSTweaks#112]
Sorry if this is the wrong place to ask, the discussions tab is empty...

**Comment by emoose** [comment]
Unfortunately not with regular DLSS DLL, but the dev DLL lets you switch them using a keybind when the HUD is showing, you can find that at https://github.com/NVIDIA/DLSS/tree/main/lib/Windows_x86_64/dev

**Comment by Nathan240600** [comment]
Hi, thanks for the reply, I've enabled the HUD but can't see which hotkey to change presets? There are only jitter, autoexposure and some other stuff.

**Comment by Nathan240600** [comment]
Oh nevermind, the RDR2 minimap was blocking it :) Thank you so much.
