### ISSUE TITLE
Is it possible to override resolution scale? E.g. make DLSS Q render at 80% instead of 67%

### ISSUE THREAD

**Issue by n00mkrad** [emoose/DLSSTweaks#13]
I'm not really happy with how big the gap between DLSS Quality (66%) and native (100%) resolution is.

Could it be possible to adjust the scale factors of each DLSS factor with this tool? For example, overriding DLSS Quality to 75% would allow 1080p -> 1440p upscaling instead of 960p -> 1080p like it is right now.

There are very few games where you can freely adjust the internal resolution, such as Control. But I'd love to have this in any DLSS game, especially Cyberpunk.

**Comment by notpentadactyl** [comment]
See this: https://github.com/emoose/DLSSTweaks/issues/2#issuecomment-1429805042
