### ISSUE TITLE
Sharpness Implementation

### ISSUE THREAD

**Issue by FattSlice** [emoose/DLSSTweaks#15]
Is it possible to add a sharpness value to the .ini? Most of the games I have used DLSS for have no way to adjust its sharpness and end up looking quite blurry with no way to improve it other than using reshade

**Comment by ShinChaosBahamut** [comment]
The most current form of DLSS doesn't have ANY sharpening (as in it's been hardcoded out, if I'm understanding correctly), so short of reverting to a dll preceeding version 2.5.1 you'll have to use something like Reshade. (personally I find it to be a net win as the DLSS sharpener was too strong for my liking, but I digress)

**Comment by emoose** [comment]
Yeah, 2.5.1 onwards seem to have disabled the DLSS sharpening, the programmer guide recommends using NIS to sharpen instead (AFAIK you can use that in NV control panel, the `Image Scaling` option lets you apply sharpening)

**Comment by FattSlice** [comment]
The response and info is greatly appreciated, I had no idea that it has been removed (read about it with 2.5.1 but figured it was just a bug).
