### ISSUE TITLE
How to change used Preset?

### ISSUE THREAD

**Issue by celloh123** [emoose/DLSSTweaks#18]
It seems like it doesnt apply when written like:
`
[DLSSPresets]
; Overrides the DLSS preset used for each quality level, set to Default to leave the preset set to whatever game/DLSS decided for it
; Or set to A / B / C / D / F to try forcing that preset instead.
; Presets were added in DLSS 3.1, similar to the old method of swapping out different DLSS DLL versions, now instead you can just set a preset for it

; Unfortunately DLSS might override these presets with ones decided by NVIDIA instead
; Enabling OverrideAppId above might help with those (at least it fixes DL2)
; (recommend testing with the dev DLSS DLL along with ngx_driver_onscreenindicator.reg to make sure the preset is being overridden properly)

; Note that some games could have graphical artefacts when certain DLSS presets are overridden onto them
; There's not much DLSSTweaks can do to help with that unfortunately, hopefully trying a different preset could help

DLAA = F
Quality = F
Balanced = F
Performance = F
UltraPerformance = F
`
Do i need to write the preset name in some other fashion?

**Comment by emoose** [comment]
That should be working afaik, what game are you trying with?

Maybe give the beta build a try if you haven't already: https://github.com/emoose/DLSSTweaks/issues/2

**Comment by celloh123** [comment]
I used with Control. It needed OverrideAppId
