### ISSUE TITLE
Quality level scaling overrides (test build available)

### ISSUE THREAD

**Issue by emoose** [emoose/DLSSTweaks#2]
E: a test build with this implemented can be found below: https://github.com/emoose/DLSSTweaks/issues/2#issuecomment-1438923998

---

ForceDLAA works by overriding the resolution DLSS tells the game to use at each quality level - it might be nice if the DLL could also let the user specify the resolution/ratio for each level too.

Not completely sure whether DLSS actually works at any ratio or not though, might have some limits in place that only let it work at the normal resolutions for each quality level, will need to look into it some more.

**Comment by doktorsleepelss** [comment]
I know Doom Eternal, Spider-man, and Deathloop support dynamic resolution scaling with DLSS, and I could see it use non-standard internal resoutions with the overlay at least.

**Comment by emoose** [comment]
So seem to have something working for this, added a `DLSSQualityRatios` section to INI where you can change the ratios:
(thanks to @doktorsleepelss for helping test it out!)

```
[DLSSQualityRatios]
; Allows overriding the ratios that DLSS uses for each quality level
; Must be enabled first (and ForceDLAA must be disabled for this to take effect)
Enable = false

; Ratios/multipliers applied to each axis of screen resolution
; Set to 1 to force this quality level to use full resolution (ie. DLAA)
; ForceDLAA must be disabled above for these to take effect!
UltraPerformance = 0.33333334
Performance = 0.5
Balanced = 0.58
Quality = 0.66666667
UltraQuality = 0.77
```

Maybe needs some more testing before I push a full release with it though, test build can be found here: 
[dlsstweaks-0.123.9beta.zip](https://github.com/emoose/DLSSTweaks/files/10733125/dlsstweaks-0.123.9beta.zip)

Not totally sure if `UltraQuality` is actually functional neither, when I tried forcing that so I could see what res DLSS would try using, it just returned 0 every time... some things I saw online mentioned it being 77% though.

**Comment by doktorsleepelss** [comment]
I tested it in a few more games. Spider-Man Remastered, Uncharted 4, RDR2, Deathloop, FIST, an Chernobolyte, Ghostwire Tokyo, an Horizon Zero dawn all work work with the custom ratios.

**Comment by doktorsleepelss** [comment]
So it turns out Mortal Shell, the one game that kept on crashing with this mod, does work with any ratio other than 1.  So I guess this game just doesn't like DLAA specifically for some reason.    You ask the other people who have trouble with dlaa to try a custom ratio.

**Comment by notpentadactyl** [comment]
Is it possible to add a ratios/multiplier for DLAA?
At least in Monster Hunter Rise at 1440p using the game's native DLAA it will run at 4k (?), at least if I'm reading the dev dll hud correctly: 

![DLAA in MH Rise](https://camo.githubusercontent.com/2ec136262caa58ae8b02d6091f2a6f8dd366d89a3b97185a96aec23ab14405b3/68747470733a2f2f61626c6f61642e64652f696d672f646c61616d6872697365717066376e2e706e67)

**Comment by HeikoMCC** [comment]
@emoose Thanks again  for adding DLAA-Support in vkQuake + prboom+  Support, it works flawlessly so far! :)

**Comment by emoose** [comment]
0.123.9beta4 release: [dlsstweaks-0.123.9beta4.zip](https://github.com/emoose/DLSSTweaks/files/10758196/dlsstweaks-0.123.9beta4.zip)

This adds a `OverrideDlssHud` option which can force enable / force disable the DLSS debug info on both release & dev DLLs.
That works by just overriding what the DLSS DLL sees when it checks the registry entry - unfortunately the DLL only seems to check this during startup though (and couldn't find a way to make it re-check, toggling DLSS didn't seem to work on any games I tried...), so changing that setting with `WatchIniUpdates` likely won't have any effect.

Hoping to find a way to hook the actual code that draws the debug info instead eventually, might make it harder to support all the different DLSS DLL versions though...

**Comment by doktorsleepelss** [comment]
I tested WatchIniUpdates from beta3 in Death Stranding and Returnal.  In Death Stranding, it would only update if I changed DLSS in-game setting first. In Returnal, WatchIniUpdates doesn't do anything

**Comment by emoose** [comment]
0.123.10beta1 release: [dlsstweaks-0.123.10beta1.zip](https://github.com/emoose/DLSSTweaks/files/10763253/dlsstweaks-0.123.10beta1.zip)

This changes the hooking lib to use safetyhook instead, and now uses spdlog for logging, should make the hooking process more safe/stable.

For that I redid the [source code layout](https://github.com/emoose/DLSSTweaks/tree/cmake) to make it use CMake, and changed all the hooks over to safetyhook versions.
It's pretty close to a rewrite really, hoping it'll still support all the same features/games that 0.123.9beta4 did but can't really say for sure, would appreciate anyone that can help try it out.

>I tested WatchIniUpdates from beta3 in a couple games. In Death Stranding, it would only update if I changed the DLSS in-game setting. In Returnal, WatchIniUpdates doesn't do anything

Hm, looks like Returnal does allow changing presets at least, but yeah couldn't get quality level scales to update - those are harder to update than presets since some games only query resolutions from DLSS at startup and never try checking again, doesn't seem there's any way for DLSS to tell the game about the resolutions either, all depends on the game asking for them :/

Maybe there's a way to make games think DLSS unloaded or something so that it'd try re-initing things, will try looking into that soon.

**Comment by HeikoMCC** [comment]
Can confirm in Crysis 3 Remastered = DLAA will be ignored, while with custom DLSS quality level - resolution ratio (as example 0.99) it does.
Crysis 1 + 2 Remastered have no Issues with DLAA , only Crysis 3 is affected.

**Comment by doktorsleepelss** [comment]
Tried  the new 0.123.10beta2 on Mortal Shell just in case, but it still crashes with DLAA. Other than that, I tested it on Death Stranding, Cyberpunk, RDR2, Spider-man, and they all seem to generally work. (I didn't test WatchIniUpdates)

OverrideDlssHud with the 3.1.1 release dll doesn't work with  Spider-man and RDR2 though. Both 0.123.10beta2 and 0.123.9beta4 have the same problem. It does work with Death Stranding and Cyberpunk.

**Comment by emoose** [comment]
0.123.10beta3 release: 
[dlsstweaks-0.123.10beta3.zip](https://github.com/emoose/DLSSTweaks/files/10778057/dlsstweaks-0.123.10beta3.zip)

Hopefully last beta for 0.123.10, was going to make a release yesterday but learned that using `_beginthreadex` instead of `CreateThread` should be safer to use, figured I should post one more beta with it just in case it might break anything.

If I don't hear of anything being broken with this in ~24 hrs I'll probably make the release then, many thanks to anyone that tries it out!

>OverrideDlssHud with the 3.1.1 release dll doesn't work with Spider-man and RDR2 though. Both 0.123.10beta2 and 0.123.9beta4 have the same problem. It does work with Death Stranding and Cyberpunk.

Do you know if the reg edit with 1024 / 400 works for spiderman/RDR2 without DLSSTweaks? Maybe they do some weird rendering that prevents it being shown at all.

**Comment by FunFrog-BY** [comment]
Thanks for this scaling feature, works great with Cyberpunk (tried 0.123.9beta, but gonna try newer release)! 0.8 is definetely better than 0.66.
Consider adding crypto address for donations.

**Comment by Sinkingsun** [comment]
Thank you, my testing is limited to Hogwarts Legacy for now. Tested with both Beta 2 and latest Beta 3; [DLSSQualityLevels] works when WatchIniUpdates is set to true, when it is set to false, the game displays the default values for quality levels regardless of what's in the ini file. When OverrideAppId is set to true, the game does not boot. The scaling feature is a great addition, in fact I hope going forward DLSS Scaling becomes a slider that one can control in games which goes from 40% to 100% (DLAA).

**Comment by emoose** [comment]
0.123.10beta4 release: [dlsstweaks-0.123.10beta4.zip](https://github.com/emoose/DLSSTweaks/files/10796510/dlsstweaks-0.123.10beta4.zip)

This should stop certain games from showing a broken Ultra Quality option now, maybe in future we can get that to work as an extra quality option in the games that show it, but for now it's better not to expose it since DLSS won't actually render properly with it yet.

**Comment by jpgsantos** [comment]
For me hogwarts legacy gets stuck at the start warning text with 0.123.10beta, with 0.123.9beta it oppens but I haven-t been able to get [DLSSQualityLevels] to work. 2070 super and 10980XE.

**Comment by aufkrawall** [comment]
Hogwarts Legacy still works for me with 0.123.10beta4.

**Comment by Dennis50300** [comment]
@emoose 
is it possible to use DLAA without deactivating the Upscaling ?

best regards

**Comment by emoose** [comment]
>with "0.123.9beta4" shadow of the Tomb Raider runnung with Preset F but after take over it "0.123.10beta4.zip" it doesn't

Hmm it works fine for me with SOTTR, that's one of the main games I use to test since it launches pretty quickly too, it does need OverrideAppId to work though.

**Comment by MashyMashZ** [comment]
> For me hogwarts legacy gets stuck at the start warning text with 0.123.10beta, with 0.123.9beta it oppens but I haven't been able to get [DLSSQualityLevels] to work. beta 10 works fine with cyberpunk. My specs are a nvidia 2070 super and intel 10980XE.

I have this as well. However, maybe one of every half dozen restarts it will work, and works fine. Otherwise it just hangs on that initial warning screen.

**Comment by Sinkingsun** [comment]
> 

Yeah as long as custom scales are chosen, you have to run Hogwarts Legacy a few times for it to work. I found clicking on the game as soon as it runs helps run it in 2 or 3 tries. But once it runs, it works fine. Do not disable auto exposure with this game as well, you can see in Hogsmeade if auto exposure is disabled the game looks awful, at least during the snowy season.

Maybe it's something @emoose can have a look at? I tried changing names as well to the ones suggested but same issue. Running DLSS 3.1.1 v2

**Comment by Sinkingsun** [comment]
> > For me hogwarts legacy gets stuck at the start warning text with 0.123.10beta, with 0.123.9beta it oppens but I haven't been able to get [DLSSQualityLevels] to work. beta 10 works fine with cyberpunk. My specs are a nvidia 2070 super and intel 10980XE.
> 
> I have this as well. However, maybe one of every half dozen restarts it will work, and works fine. Otherwise it just hangs on that initial warning screen.

Yeah as long as custom scales are chosen, you have to run Hogwarts Legacy a few times for it to work. I found clicking on the game as soon as it runs helps run it in 2 or 3 tries. But once it runs, it works fine. Do not disable auto exposure with this game as well, you can see in Hogsmeade if auto exposure is disabled the game looks awful, at least during the snowy season.

Maybe it's something @emoose can have a look at? I tried changing names as well to the ones suggested but same issue. Running DLSS 3.1.1 v2

**Comment by BitGrub** [comment]
Can't get custom DLSSQualityLevels to work in Hogwarts Legacy with the latest public release 0.123.11

**Comment by emoose** [comment]
Posting new test builds in the Ultra Quality issue: https://github.com/emoose/DLSSTweaks/issues/22#issuecomment-1442839063

There's a small chance it might help with Hogwarts Legacy too, if anyone tries it let me know how it went.

**Comment by sam3000** [comment]
> Can't get custom DLSSQualityLevels to work in Hogwarts Legacy with the latest public release 0.123.11

works fine here.  Hogwarts even shows my 78% quality resolution in the in-game settings.
