### ISSUE TITLE
Working With Hellblade: Senua's Sacrifice.

### ISSUE THREAD

**Issue by KedarWolf** [emoose/DLSSTweaks#21]
Needs to be put in this folder. 

C:\Program Files (x86)\Steam\steamapps\common\Hellblade\HellbladeGame\Binaries\Win64

DLL needs to be renamed 'XInput1_3.dll'.

`DLSSTweaks v0.123.8, by emoose: DLL wrapper loaded, watching for DLSS library load...

DLSSTweaks v0.123.8, by emoose: DLL wrapper loaded, watching for DLSS library load...

DLSSTweaks v0.123.8, by emoose: DLL wrapper loaded, watching for DLSS library load...
Applied _nvngx.dll DLL export hooks, waiting for game to call them...
DLSS functions found & parameter hooks applied!
Settings:
 - ForceDLAA: true
 - ForceAutoExposure: true
 - OverrideAppId: true
`

**Comment by emoose** [comment]
Added to the wiki, thanks for the info :+1:
