### ISSUE TITLE
Works not with Hitman 3 (for me)

### ISSUE THREAD

**Issue by Hitman891** [emoose/DLSSTweaks#26]
Hello,

I tried this mod with Hitman 3. For me, it does not work. I put the files in the main folder. But in the dlsstweaks.log file, it only reads:

[2023-02-23 18:42:25.784] [info] DLSSTweaks v0.123.11, by emoose: DLL wrapper loaded, watching for DLSS library load... 

In other games like Ready or not, it works fine. What Did I do wrong? Please help.

Thanks!

**Comment by emoose** [comment]
Maybe the game is loading our DLL in too late, after DLSS was already loaded in, could try renaming our DLL to one of the other ones mentioned in INI, hopefully game might load one of those in earlier.

**Comment by Hitman891** [comment]
Sadly, it does not work with any of the proposed renamed *.dll files. Any suggestions?

**Comment by emoose** [comment]
Just to make sure, do you have DLSS enabled in-game? probably only loads in if that's enabled.

Also are you using recent nvidia drivers? AFAIK older ones are missing things that DLSSTweaks need to work.

**Comment by Hitman891** [comment]
Yes, DLSS in enabled in-game and I use the most recent Nvidia drivers.

**Comment by aufkrawall** [comment]
Did you put the files into "Retail" folder? Should definitely work there.

**Comment by Hitman891** [comment]
If I put the files in the "Retail" Folder, it still does not work. Then, the dlsstweaks.log file stays empty and has no entries at all.

**Comment by aufkrawall** [comment]
The log indeed doesn't contain anything (well, I guess that shouldn't be), but it should still work:
![hitman3_2023_02_24_11_22_13_728](https://user-images.githubusercontent.com/13510490/221169219-f5cef16f-55bb-4165-a716-8399b562963a.png)

**Comment by Hitman891** [comment]
I just tested it with this overlay, and it really works (DLAA enabled), even though the log file stays empty. 
Thanks for the help. How do I change the DLSS preset to F in the ini.file?
