### ISSUE TITLE
Rockstar Games Launcher Red Dead Redemption 2 issue fix idea/Disable DLSS sharpening

### ISSUE THREAD

**Issue by xuru-thor** [emoose/DLSSTweaks#29]
Currently vanilla RDR2 uses DLSS version 2.2.10. As far as I know, the DLL hasn't been officially updated a single time ever since it was implemented into the game, in the July 2021 update. Steam users can easily update their DLSS by replacing the DLL in the directory, without any further worry. However, users who own the game on the Rockstar Games Launcher have to constantly worry about the replaced DLL being automatically downgraded by updates, and the game's directory folder having its permissions completely screwed over by said updates. The only way to play the game on RGL with an updated DLSS file is to wait for the game to finish downgrading itself, clicking the "Play" button inside the launcher, and then after a few seconds finally replacing the file in the directory with the updated DLSS DLL, right before the game opens. Keep in mind, the next time you want to play the game again you will have to let the launcher update the game to downgrade the file once again, and do the same process all over again.

  So here's my idea. What if DLSSTweaks automatically updated the DLSS DLL to the latest version every time the game was booted up, right before it actually opens, and automatically fixed the directory folder permissions? I feel like this would be the perfect solution for this issue RGL players have been having for months.

  Also, completely unrelated to this issue, but an option to disable the DLSS sharpening would be an awesome addition.

**Comment by Treemcgee324** [comment]
For the issues with Rockstar games launcher replacing the DLSS dll, you might be interested in this: https://github.com/emoose/DLSSTweaks/issues/22#issuecomment-1443624026

It's a version of DLSS Tweaks that has an option called `OverrideDlssDll` that allows you to tell a game to load the DLSS dll from somewhere other than the game directory. For example, you could have the DLSS 3.1 dll on your desktop and DLSS tweaks will load it into Red Dead Redemption 2 instead of the one bundled with the game. And since the DLSS dll is outside of Red Dead Redemption 2's installation folder, it won't be removed/replaced by the Rock Star Games launcher.

**Comment by xuru-thor** [comment]
Oh my, that is exactly what I wanted! I would close this issue right this instant if it wasn't for the matter of the suggestion of disabling the DLSS sharpening.

**Comment by emoose** [comment]
Yeah as @Treemcgee324 mentioned you should be able to use that to help with RDR2, it seemed to work fine on my RGL version at least.

Auto-updating is a nice idea, but I'm not really sure how well I could make it do that securely, 3.1.1 does apparently support some kind of OTA update now though, maybe once they start pushing updates with that we can find some way to force it to update automatically.

For DLSS sharpening, if you update to DLSS 2.5.1 or 3.1.1 those both should have sharpening disabled, IMO there's probably not that much need to use an older DLSS than 3.1.1 now that they merged all the different DLSS models as the A-F presets, but if there is some 2.x version that people are still staying with maybe it could be worth adding a way to override it.

**Comment by xuru-thor** [comment]
I can't seem to get the override DLL setting to work. Tried with the dev file and the watermark didn't show up. Am I doing something wrong?
![image](https://user-images.githubusercontent.com/71799959/221365485-fb6d2578-d69d-4cde-b1a1-11b626b6440c.png)
![image](https://user-images.githubusercontent.com/71799959/221365524-b5fa94fe-0fe9-4cd4-bc06-cd2b54a83c38.png)

Also, I didn't know the latest version already had sharpening disabled. That's perfect then.

**Comment by Treemcgee324** [comment]
@xuru-thor, from my understanding you need to specific a full path to the dll, with quotation marks. And forward slashes need to be back slashes. So it should be:

`OverrideDlssDll = "C:/Program Files/Rockstar Games/Red Dead Redemption 2/DLSS 3.1.1 v2/nvngx_dlss_new.dll`

**Comment by xuru-thor** [comment]
Thanks, but that didn't work either. I also tried keeping the back slashes but no luck.
![image](https://user-images.githubusercontent.com/71799959/221384383-87013ab9-105f-4428-8b47-757f76b7fccb.png)

**Comment by Treemcgee324** [comment]
I'm sorry, I don't know how to help. That worked for me (although, I was testing Cyberpunk 2077, not Red Dead Redemption 2)

One thing, if you haven't done this already, make sure DLSS tweaks is working before testing the OverrideDlssDll option?

**Comment by dkflint723** [comment]
There is another git project that does exactly what you're looking for @xuru-thor: https://github.com/Bullz3y3/RDR2_DLSS_Replacer

**Comment by emoose** [comment]
When I added that I only tried it by renaming 3.1.1 `nvngx_dlss.dll` to `nvngx_dlss_new.dll`, copying the renamed file next to RDR2.exe, and then setting the option as `OverrideDlssDll = nvngx_dlss_new.dll`, for me that seemed to let it work at least.

Full path should have worked though really, but I didn't test that for myself, maybe there's an issue with spaces in paths that I need to look into.

**Comment by doktorsleepelss** [comment]
dxgi.dll needs to be renamed XInput9_1_0.dll for RDR2.

**Comment by xuru-thor** [comment]
> dxgi.dll needs to be renamed XInput9_1_0.dll for RDR2.

This did the trick! The OverrideDll setting is working just fine, I just didn't notice the entirety of Tweaks wasn't working. Thank you everyone for all the help, and thank you emoose for this wonderful tool!

> There is another git project that does exactly what you're looking for @xuru-thor: https://github.com/Bullz3y3/RDR2_DLSS_Replacer

Thanks for the tip, but now that DLSSTweaks is working perfectly, there is no need for any other tools.
