### ISSUE TITLE
0.123.11 NOT working whilst 0.123.8 working

### ISSUE THREAD

**Issue by erdo4** [emoose/DLSSTweaks#32]
For all my games, I have been using 0.123.8. All working great without issue, DLAA+F preset etc.

Updated to 0.123.11 for all my games. Same setup, same ini. However, it just does not work with this version.

- in the log, for some games it's blank, for other games it can not find the dlss.dll
- All .ini are the same. Even when I only change the DLSSTweaks .dll but keep the ini's, its not working. Using 0.123.8's dll makes it working again. So its definetly a .dll problem.

What I think is, it just doesn't load the DLSSTweak's DLL into the game. I'm not sure why tho. Whilst its working great with previous version.

Games that was working for 0.123.8 but not working with 0.123.11 now:
-Ready or Not
-Hitman 3
-Red Dead Redemption 2

Tested both 3.1.1 Public and 3.1.1 DEV version DLL

**Comment by erdo4** [comment]
I'm using 516.59

Should I update my driver?

**Comment by emoose** [comment]
Aha yeah that's probably it, the user I mentioned was actually using the exact same version and had same issue with it not applying, after they updated to 528.49 it worked fine.

**Comment by erdo4** [comment]
> Aha yeah that's probably it, the user I mentioned was actually using the exact same version and had same issue with it not applying, after they updated to 528.49 it worked fine.

Just updated my driver to 528.49 and now it's working fine. Thank you!
