### ISSUE TITLE
Mount & Blade II: Bannerlord works well

### ISSUE THREAD

**Issue by jimbojammesi** [emoose/DLSSTweaks#41]
Using dlsstweak's default dxgi.dll, DLSS 3.1.1 dll, and ForceDLAA setting = true, DLAA is working for Bannerlord. Works in singleplayer and any multiplayer mod which does not use BattlEye anti cheat (works fine in cRPG mod). Trying to launch native multiplayer Bannerlord will crash because of BattlEye flagging the dxgi.dll.

Visual quality is great and does not suffer from the same scaling/ghosting problems that current patch Bannerlord has when using dlss.

**Comment by emoose** [comment]
Added to the wiki, thanks for the info :+1:
