### ISSUE TITLE
Hi-Fi RUSH (WinStore/Gamepass): ForceDLAA appears to be working

### ISSUE THREAD

**Issue by motomola** [emoose/DLSSTweaks#45]
DLSS 3.1.1 dll from techpowerup replaced the original game dll in:
Hi-Fi RUSH\Content\Engine\Plugins\Runtime\Nvidia\DLSS\Binaries\ThirdParty\Win64

dxgi.dll and dlsstweaks.ini placed with EXE in:
Hi-Fi RUSH\Content\Hibiki\Binaries\WinGDK

![dlss](https://user-images.githubusercontent.com/127750356/224701235-9b8b1bd8-48f6-420a-8596-edf6afcda02e.jpg)

**Comment by emoose** [comment]
Added to wiki, thanks for the info 👍

**Comment by 333hronos** [comment]
Thanks! Finally no more ghosting with dlss with preset F
