### ISSUE TITLE
Vulkan testing

### ISSUE THREAD

**Issue by emoose** [emoose/DLSSTweaks#5]
Latest commit added hooks that should let Vulkan titles work with it (eg. RDR2), I don't currently have any VK games to try with myself though, would appreciate anyone trying it out.

Build can be found here: 
[dlsstweaks-0.123.8.zip](https://github.com/emoose/DLSSTweaks/files/10726929/dlsstweaks-0.123.8.zip)

If you try it out let me know how it goes, either here or on the reddit post: https://www.reddit.com/r/nvidia/comments/111e0xi/dlsstweaks_dll_hook_that_can_force_dlaa_onto/

**Comment by doktorsleepelss** [comment]
Can confirm it works.

**Comment by emoose** [comment]
Nice, I've pushed that as a release then.

Not really sure how complete the VK hooks are though, could still be some VK titles that have issues, if anyone finds one feel free to shout at me here.

**Comment by aufkrawall** [comment]
Also works in Doom Eternal for me.

**Comment by emoose** [comment]
Seems to be stable enough, I'll close this now then, if anyone does run into any issues with a vulkan game feel free to make a post about it.
