### ISSUE TITLE
nvngx.dll isn't included

### ISSUE THREAD

**Issue by rickvanoverbeek** [emoose/DLSSTweaks#60]
Where can I find the nvngx.dll file? It isn't included in my download DLSSTweaks-0.200.5-beta3

**Comment by donizettilorenzo** [comment]
https://www.techpowerup.com/download/nvidia-dlss-dll/

**Comment by rickvanoverbeek** [comment]
Thanks! But that only includes nvngx_dlss.dll and not nvgnx.dll?
According to a post on Assetto Corsa forum, I need both files.

dlsstweaks.ini and nvngx.dll have to be in folder "Assetto Corsa Competizione\AC2\Binaries\Win64"

The nvngx_dlss.dll in version 3.x has to be in the "Assetto Corsa Competizione\AC2\Plugins\DLSS\Binaries\ThirdParty\Win64"

**Comment by emoose** [comment]
The DLLs for this are on nexusmods: https://www.nexusmods.com/site/mods/550?tab=files

Unfortunately that does need a nexusmods account to download though AFAIK, I'm looking into other methods for it too.

**Comment by donizettilorenzo** [comment]
nvngx is in DLSSTweaks package

**Comment by Ouwerkerk78** [comment]
> The DLLs for this are on nexusmods: https://www.nexusmods.com/site/mods/550?tab=files
> 
> Unfortunately that does need a nexusmods account to download though AFAIK

No nvngx.dll in download on nexus
