### ISSUE TITLE
Sharping settings in ini file

### ISSUE THREAD

**Issue by dmustimenko** [emoose/DLSSTweaks#61]
Hello. First of all thank you very much for your great job!
But I have one request - could you add sharping settings to ini file? For now I use your tweaks in RDR 2 and inner sharping settings do not work with your dll.
Thanks!

**Comment by Azulath** [comment]
As to my knowledge, sharpening has been removed from DLSS in newer version (2.5.1) as it did not meet the quality requirements.

Thus, developers have to use their own implementation, like CDPR did with Cyberpunk 2077, or users need to use GFE's sharpening.

**Comment by dmustimenko** [comment]
Oh, got it @Azulath . Thank you for the explanation.
