### ISSUE TITLE
Cannot Find nvngx.dll

### ISSUE THREAD

**Issue by murtaxa-taha** [emoose/DLSSTweaks#65]
Help I'm going crazy. I downloaded the zip file but can't find the included nvngx.dll file anywhere! I can see the dllstweaks.ini file but I searched the whole folder using windows and can't find the nvngx.dll file that I need to copy. I may just be quite dumb please help!

**Comment by emoose** [comment]
The files from github are just source code, DLL itself is hosted on nexusmods: https://www.nexusmods.com/site/mods/550?tab=files

**Comment by Cleric670** [comment]
It's actually not available at that link anymore, at least with the current version. You have a post stating how it isn't included in the file due to not wanting the signature enabled stuff packaged in that ZIP.

Where can we get a copy of nvngx.dll in May 2024?
