### ISSUE TITLE
Request to fix UE4.26 Tower of Fantasy from the OverrideAutoExposure bug problem.

### ISSUE THREAD

**Issue by SamuelMeaw** [emoose/DLSSTweaks#67]
I found in the latest DLSSTweaks 0.200.5-beta4 release，when:
ForceDLAA = true
OverrideAutoExposure = 0
OverrideDlssHud = 1
DLAA = D
Keep other settings as default, you can see that Autoexposure: OFF by default:
https://ibb.co/KDNgdw3
When I change the value of OverrideAutoExposure from 0 to 1, and the following warning appears in dlsstweaks.log:
https://ibb.co/HNmrZcR
But when OverrideAutoExposure = 0 and VerboseLogging = true,the following debug error message appears:
https://ibb.co/pjyKNj4
According to my judgment, Tower of Fantasy does not AutoExposure effect by default. After force AutoExposure to be enabled, it will be better graphics quality and less artifacts.Force AutoExposure also works perfect in previous versions.I hope the author will fix the bug warning problem when I set OverrideAutoExposure = 1.

**Comment by emoose** [comment]
Those repeated messages are definitely a issue, looks like game is switching between textures for that rapidly, which is making DLSSTweaks write about it each time into the log.
(this rapid switching could also be why AutoExposure gives better results, maybe DLSS doesn't like the texture being changed so much, with AutoExposure enabled it would ignore that texture and use calculated one instead, not sure how true that is though)

Could you try this build and see if it helps? It might still print 1 or 2 warnings into log file, but shouldn't spam it any more:
[dlsstweaks_0.200.5.5.zip](https://github.com/emoose/DLSSTweaks/files/11184278/dlsstweaks_0.200.5.5.zip)

**Comment by SamuelMeaw** [comment]
> 那些重复的消息肯定是个问题，看起来游戏在 2 种不同的曝光纹理之间快速切换，这使得 DLSSTweaks 每次都将其写入日志。
> 
> （这种快速切换也可能是 AutoExposure 提供更好结果的原因，也许 DLSS 不喜欢纹理变化太多，启用 AutoExposure 后它会忽略该纹理并使用计算的纹理）
> 
> 你能试试这个构建，看看它是否有帮助吗？它可能仍会在日志文件中打印 1 或 2 个警告，但不应再向其发送垃圾邮件： [dlsstweaks_0.200.5.5.zip](https://github.com/emoose/DLSSTweaks/files/11184278/dlsstweaks_0.200.5.5.zip)

Thanks, it really works!
https://ibb.co/S7V5rRH
