### ISSUE TITLE
Monster Hunter Rise (1446780) breaks with DLAA

### ISSUE THREAD

**Issue by notpentadactyl** [emoose/DLSSTweaks#9]
In Monster Hunter Rise (1446780) the screen is black when setting `ForceDLAA = true`, the UI is working fine (as expected).

![everything but the UI is black](https://abload.de/img/20230214130601_1oticf.jpg)

---

On a side note: the game also needs `OverrideAppId = true` if you want to override the DLSSPresets for `Quality` to `C` e.g.

**Comment by emoose** [comment]
Could you try using ForceDLAA with the build at https://github.com/emoose/DLSSTweaks/issues/2#issuecomment-1429805042? 

There was a small issue with the hook code which that build also includes fix for, might help some games that had black-screen issues like this, but not completely sure.

**Comment by notpentadactyl** [comment]
same issue with the following config:
```
[DLSS]
ForceDLAA = true
OverrideAppId = true
[DLSSPresets]
DLAA = F
```
---
and with the following config:
```
[DLSS]
OverrideAppId = true
[DLSSQualityRatios]
Enable = true
Quality = 1.0
[DLSSPresets]
Quality = F

```
![quality 1.0](https://abload.de/img/20230214165819_1vwc3z.jpg)
(screenshot from the last one)

**Comment by doktorsleepelss** [comment]
Check if it works with any ratio other than 1. Try 0.95 for example. Mortal Shell is game that refused to work with DLAA or 1, but it does with any other ratio. ForceDLAA shoul be off of course

**Comment by ShinChaosBahamut** [comment]
Correct me if I'm wrong, but doesn't Monster Hunter Rise have native DLAA support?

**Comment by notpentadactyl** [comment]
> Correct me if I'm wrong, but doesn't Monster Hunter Rise have native DLAA support?
> 
> edit: Yep, it does. (in the anti-aliasing section)

You are indeed correct. I guess we can close this issue?

![DLAA in MH Rise](https://abload.de/img/dlaamhriseqpf7n.png)

**Comment by notpentadactyl** [comment]
FWIW: without DLSSTweaks the _native_ DLAA in this game defaults to the "D" preset, so this tool is still useful to get the "F" preset.

**Comment by emoose** [comment]
Yeah guess we can close this then, kinda weird that the in-game DLAA worked while our forced version didn't though, guess maybe something about it confused the game.
