### ISSUE TITLE
Modify Ultra Quality preset?

### ISSUE THREAD

**Issue by NineKain** [emoose/DLSSTweaks#99]
Cant seem to find the option on the config, just DLAA + all the other options, but not Ultra Quality

**Comment by emoose** [comment]
The 0.200.7 beta ver should include settings for UQ presets: https://github.com/emoose/DLSSTweaks/issues/88#issuecomment-1684184758

Not totally sure how well that works though since I don't have any games that show the UQ option atm.

**Comment by NineKain** [comment]
Thats fine, I can test, do you know where this beta is located? Can't find it here or in nexusmods
